'use client'
import { Heebo, Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import StoreProvider from "./state/StoreProvider";
import { store, persistor } from "./state/Store";
import { PersistGate } from "redux-persist/integration/react";
import { injectStore } from "./utils/apiUser";
import { ToastContainer } from "react-toastify";
const heebo = Heebo({ subsets: ["latin"] });

// export const metadata = {
//   title: "Apiko Store",
//   description: "Generated by create next app",
// };

console.log("Injecting store..."); // Додаємо логування
injectStore(store)


export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={heebo.className} suppressHydrationWarning={true} >
          <StoreProvider>
            <PersistGate loading={null} persistor={persistor}>
              <div className="min-h-screen">
                <Header/>
                {children}
                <Footer/>
              </div>
            </PersistGate>
          </StoreProvider>
          <ToastContainer style={{ width: "584px", height: "60px", marginTop: "82px"}} limit={5}/>

        </body>
      </html>
  );
}
